FROM nvidia/cuda:11.0.3-devel-ubuntu20.04

# Set lang
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

# Set python env vars
ENV PYTHONUNBUFFERED=1 \
    # Prevents python creating .pyc files
    PYTHONDONTWRITEBYTECODE=1 \
    \
    # Pip
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Install python 3.9
ENV DEBIAN_FRONTEND=noninteractive

# Rotating Keys
RUN rm /etc/apt/sources.list.d/cuda.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    software-properties-common \
    git \
    curl \
    git-lfs \
    ssh \
    python3.9 \
    python3.9-dev \
    python3.9-venv \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*